# Generated by Django 6.0.2 on 2026-04-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(max_length=1)),
                ('category', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('general', 'General Knowledge'), ('science', 'Science'), ('history', 'History')], default='general', max_length=50)),
            ],
        ),
    ]
